import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { SessionProvider } from 'next-auth/react'; // Import SessionProvider
import Theme from '@/components/Theme';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          {' '}
          {/* Wrap children with SessionProvider */}
          <Theme
            wrapper="body"
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            style={{ margin: 0 }}
          >
            {children}
          </Theme>
        </SessionProvider>
      </body>
    </html>
  );
}
