name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: SSH into remote server and execute commands
      - name: Executing remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_SERVER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            # Navigate to the app directory
            mkdir -p ~/sites/bw-campaign-tool-staging
            cd ~/sites/bw-campaign-tool-staging

            # Fetch the latest changes from the staging branch
            git fetch origin staging
            git reset --hard origin/staging

            # Install dependencies
            pnpm install

            # Build the application
            pnpm run build

            # Restart the PM2 process
            if pm2 list | grep -q bw-campaign-tool-staging; then
              pm2 restart bw-campaign-tool-staging
            else
              pm2 start npm --name bw-campaign-tool-staging -- run start
            fi
